name: Flutter Web Build ğŸš€

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¾ Checkout repository
        uses: actions/checkout@v3

      - name: âš™ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: ğŸ“¦ Get dependencies
        run: flutter pub get
        working-directory: frontend

      - name: ğŸŒ Build Flutter web
        run: flutter build web --release
        working-directory: frontend

      - name: ğŸš€ Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPAKTOK_E7866 }}"
          channelId: live
          projectId: spaktok-e7866
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
